version: "3.4"

services:
  mypayslip:
    container_name: mypayslip
    image: ghcr.io/lukaspatzke/mypayslip:latest
    restart: always
    expose:
      - 80
    networks:
      - proxy
    command:
      - "--user=${MYPAYSLIP_USER}"
      - "--password=${MYPAYSLIP_PASS}"
      - "--seafile-token=${SEAFILE_TOKEN}"
      - "--host=:80"

networks:
  proxy:
      external: true