version: "3.7"

volumes:
    node-red:
    mosquitto:
    homebridge:

services:
    homebridge:
        image: homebridge/homebridge
        container_name: homebridge
        restart: always
        network_mode: host
        environment: 
          TZ: Europe/Berlin
          HOMEBRIDGE_CONFIG_UI: 1
          HOMEBRIDGE_CONFIG_UI_PORT: 9012
          PUID: 1000
          PGID: 1000
          TERMINATE_ON_ERROR: 1 
          ENABLE_AVAHI: 0
        volumes: 
          - homebridge:/homebridge          
        labels: 
          - "traefik.enable=true"
          - "traefik.http.services.homebridge.loadbalancer.server.port=9012"
          - "traefik.http.routers.homebridge.rule=Host(`homebridge.l3s.io`)"
          - "traefik.http.routers.homebridge.service=homebridge"
          - "traefik.http.routers.homebridge.entrypoints=websecure"
          - "traefik.http.routers.homebridge.middlewares=local-ip"
          - "traefik.http.services.ambienthue.loadbalancer.server.port=3000"
          - "traefik.http.routers.ambienthue.rule=Host(`ambienthue.l3s.io`)"
          - "traefik.http.routers.ambienthue.service=ambienthue"
          - "traefik.http.routers.ambienthue.entrypoints=websecure"
          - "traefik.http.routers.ambienthue.middlewares=local-ip"

    node-red:
      image: nodered/node-red:latest-12
      container_name: node-red
      restart: always
      environment:
        - TZ=Europe/Berlin
        - NODE_RED_CREDENTIAL_SECRET=$NODE_RED_CREDENTIAL_SECRET
        - NODE_RED_ENABLE_PROJECTS=true
      networks:
        - proxy
        - default
      volumes:
        - node-red:/data
        - ./node-red/.ssh:/usr/src/node-red/.ssh
      labels: 
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.node-red.rule=Host(`node-red.l3s.io`)"
        - "traefik.http.services.node-red.loadbalancer.server.port=1880"
        - "traefik.http.routers.node-red.entrypoints=websecure"
        - "traefik.http.routers.node-red.middlewares=auth"

    mosquitto:
      image: "eclipse-mosquitto"
      container_name: "mosquitto"
      restart: always
      expose:
        - "1883"
        - "9001"
      networks:
        - proxy
      volumes:
        - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
        - mosquitto:/mosquitto/data
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"

        - "traefik.tcp.routers.mqtt.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.mqtt.entrypoints=mqtt"

        - "traefik.tcp.routers.mqtts.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.mqtts.entrypoints=mqtts"
        - "traefik.tcp.routers.mqtts.tls.certresolver=letsencrypt"
        - "traefik.tcp.services.mqtt.loadbalancer.server.port=1883"

networks:
  proxy:
      external: true
  default: