scrape_configs:
  - job_name: 'federate'
    scrape_interval: 15s

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{job="flora"}'

    static_configs:
      - targets:
        - 'prometheus:9090'
