version: '3.7'

services:
    kong-migrations:
        image: kong:latest
        entrypoint: sh -c "sleep 10 && kong migrations bootstrap -v"
        environment:
          - KONG_DATABASE=postgres
          - KONG_PG_HOST=kong-db
          - KONG_PG_PORT=5432
          - KONG_PG_DATABASE=kong
          - KONG_PG_USER=kong
          - KONG_PG_PASSWORD=${KONG_DB_PASSWORD}
        networks:
        - networking_kong
        restart: on-failure

networks:
    networking_kong:
        external: true
