docker run --rm \
  --name=weatherflow-collector-home-remote-import \
  -e TZ=Europe/Berlin \
  -e WEATHERFLOW_COLLECTOR_COLLECTOR_TYPE=remote-import \
  -e WEATHERFLOW_COLLECTOR_DEBUG=false \
  -e WEATHERFLOW_COLLECTOR_DEBUG_CURL=false \
  -e WEATHERFLOW_COLLECTOR_FUNCTION=import \
  -e WEATHERFLOW_COLLECTOR_HEALTHCHECK=true \
  -e WEATHERFLOW_COLLECTOR_HOST_HOSTNAME=srv \
  -e WEATHERFLOW_COLLECTOR_IMPORT_DAYS=10 \
  -e WEATHERFLOW_COLLECTOR_INFLUXDB_PASSWORD=x8egQTrf4bGl8Cs3XGyF1yE0b06pfgJe \
  -e WEATHERFLOW_COLLECTOR_INFLUXDB_URL=http://srv:8086/write?db=weatherflow \
  -e WEATHERFLOW_COLLECTOR_INFLUXDB_USERNAME=weatherflow \
  -e WEATHERFLOW_COLLECTOR_STATION_ID="56516" \
  -e WEATHERFLOW_COLLECTOR_THREADS=4 \
  -e WEATHERFLOW_COLLECTOR_TOKEN=edb8b280-95a9-4e54-86da-f4b65d099e1f \
  lux4rd0/weatherflow-collector:latest


